---
title: "Central Oregon Hashes"
output: blastula::blastula_email
editor: visual
---

# Central Oregon Hashes

```{r}
#| echo: false
#| warning: false

# This code uses the 'ical' library to parse events from a Google Calendar and perform various data manipulations. Install from GitHub as the CRAN version does not import creation dates.
# Ensure that the 'ical' and 'tidyverse' libraries are installed before running this code.

#if(!require(ical)) 
#  remotes::install_github("petermeissner/ical")
#if(!require(tidyverse)) 
#  install.packages("tidyverse")
#if(!require(stringi)) 
#  install.packages("stringi")

# Sys.setenv(TZ='GMT') # Uncomment to test on GitHub Action timezone

library("ical") 
library("dplyr")
library("lubridate")
library("stringr")
library("stringi")

# Parse events from the specified Google Calendar URL
events <- ical_parse_df("https://calendar.google.com/calendar/ical/6ureum96qhgf13kj820i61ovq8%40group.calendar.google.com/public/basic.ics")

 # events <- ical_parse_df("https://calendar.google.com/calendar/ical/cae3r4u2uhucmmi9rvq5eu6obg%40group.calendar.google.com/public/basic.ics")

# Data manipulation: 
# - Replace newline characters in the description with '<br>'
# - Extract day, date, time, and location information
# - Set default values for missing location and description
# - Sort events by start date
events <- 
  events |>
  mutate(description = gsub("\n", "<br>", description),
         dtstart = 
           if_else(hour(dtstart) == 0 & hour(dtend) == 0,
                   # convert dtstart from GMT to PST or PDT
                   lubridate::force_tz(dtstart, tzone = "America/Los_Angeles"),
                   dtstart),
         day = as.character(wday(dtstart, label = TRUE, abbr = FALSE)),
         date = format(dtstart, format = "%B %d"),
         time = if_else(hour(dtstart) == 0 & hour(dtend) == 0,
                           "TBD", 
                        format(dtstart, format = "%I:%M %p")),
         location = if_else(is.na(location), "TBD", location),
         description = if_else(is.na(description), "Details to follow", description),
         # find the location of the last <br> in the description field that comes before the string "email group" and replace everything after it with a space.
         emailgroup_location = str_locate(description, "email group"),
         last_br_before_email = 
           stri_locate_last_fixed(substr(description, 
                                         1,      
                                         emailgroup_location[, "start"]),
                                  "<br>"),
         description = if_else(is.na(last_br_before_email[, "start"]),
                               description,
                               substr(description, 
                                      1,
                                      last_br_before_email[, "start"]-1)
                               ),
         daysuntill = as.numeric(difftime(as.Date(dtstart), 
                                          as.Date(Sys.Date()),
                                          units = "days"))) |>
  arrange(dtstart)

# Identify events triggering in 10 days
trigger_10 <- 
  events |>
  filter(daysuntill == 10)

# Identify events triggering in 10 days
trigger_2 <- 
  events |>
  filter(daysuntill == 2)

# Identify events with updates:
# - Upcoming events within the next 2 days
# - Events with new updates in the last 24 hours
updates <- 
  events |>
  filter(dtstart > Sys.Date(),
         daysuntill < 2 &
         difftime(last.modified, Sys.Date(), units = "hours") > -24)

# Identify events happening next two days:
# - Future events within the next 2 days
# - Exclude events already marked with updates
twoday <- 
  events |>
  filter(as.Date(dtstart) > Sys.Date() &
         daysuntill == 2 &
         !uid %in% updates$uid) 

# Identify events happening next week:
# - Future events within the next 10 days
# - Exclude events already marked with updates
nextweek <- 
  events |>
  filter(as.Date(dtstart) > Sys.Date() &
         daysuntill <= 10 &
         !uid %in% updates$uid &
         !uid %in% twoday$uid) 


# Identify events happening 10 days from now
upcoming <- 
  events |>
  filter(dtstart > Sys.Date() + 10 &
         !uid %in% nextweek$uid &
         !uid %in% twoday$uid)

```

```{r}
#| echo: FALSE
#| results: 'asis'

# Display updates information if there are any updates
if(nrow(updates) > 0) {
  cat('### ⚠️ Late breaking updates!')
  cat('  \n')
  cat("Sometimes plans change, details are missed, or cool things come together at the last minute.  Here are updates we didn't want you to miss.")

  # Iterate through each update and format the display
  for (i in 1:nrow(updates)) {
    # Display the event summary with bold orange color
    cat('  \n')
    cat(paste0("  \n", 
               '<span style="color:#8E2600;font-weight:bold">',
               updates[i, "summary"],
               '</span>'))
    
    # Display event details including date, time, location, and description
    cat("  \n", "**Date:**", updates[i, "day"], updates[i, "date"])
    cat("  \n", "**Time:**", updates[i, "time"])
    cat("  \n", "**Where:**", updates[i, "location"], "\n")
    cat("  \n", updates[i, "description"], "\n")
    cat('\n')
  }
  cat('---')
}

```

```{r}
#| echo: FALSE
#| results: 'asis'

# Display upcoming events information if there are any events next week
if(nrow(twoday) > 0) {
  cat('### ⏰ Just a reminder')

  # Iterate through each upcoming event and format the display
  for (i in 1:nrow(twoday)) {
    # Display the event summary with bold orange color
    cat('  \n')
    cat(paste0("  \n", 
               '<span style="color:#8E2600;font-weight:bold">',
               twoday[i, "summary"],
               '</span>'))
    
    # Display event details including date, time, location, and description
    cat("  \n", "**Date:**", twoday[i, "day"], twoday[i, "date"])
    cat("  \n", "**Time:**", twoday[i, "time"])
    cat("  \n", "**Where:**", twoday[i, "location"], "\n")
    cat("  \n", twoday[i, "description"], "\n")
    cat('\n')
  }
  cat('---')
}

```

```{r}
#| echo: FALSE
#| results: 'asis'

# Display upcoming events information if there are any events next week
if(nrow(nextweek) > 0) {
  cat('### 👣 Cumming soon...')

  # Iterate through each upcoming event and format the display
  for (i in 1:nrow(nextweek)) {
    # Display the event summary with bold orange color
    cat('\n')
    
    # Display the event summary with bold red color
    cat(paste0("  \n", 
               '<span style="color:#8E2600;font-weight:bold">',
               nextweek[i, "summary"],
               '</span>'))
    
    # Display event details including date, time, location, and description
    cat("  \n", "**Date:**", nextweek[i, "day"], nextweek[i, "date"])
    cat("  \n", "**Time:**", nextweek[i, "time"])
    cat("  \n", "**Where:**", nextweek[i, "location"], "\n")
    cat("  \n", nextweek[i, "description"], "\n")
    cat('\n')
  }
  cat('---')
}

```

### 📆 More shenanigans ahead!

<sub>*(head? who said head??)*<sub>

```{r}
#| echo: FALSE
#| results: 'asis'
# Display information for upcoming events if there are any
if(nrow(upcoming) > 0) {
  cat('\n')
  cat('\n')
  
  # Iterate through each upcoming event and format the display
  for (i in 1:nrow(upcoming)) {
    cat('\n')
    
    # Display the event summary with bold red color
    cat(paste0("  \n", 
               '<span style="color:#8E2600;font-weight:bold">',
               upcoming[i, "summary"],
               '</span>'))
    
    # Display event details including date, time, location, and description
    cat("  \n", "**Date:**", upcoming[i, "day"], upcoming[i, "date"])
    cat("  \n", "**Time:**", upcoming[i, "time"])
    cat("  \n", "**Where:**", upcoming[i, "location"], "\n")
    cat("  \n", upcoming[i, "description"], "\n")
    cat('\n')
  }
} else {
  # Display a message if there are no other upcoming events
  cat("No other upcoming events. [Sign up to hare!](mailto:centraloregonhash@gmail.com?subject=Interested%20in%20haring)")
}

```

------------------------------------------------------------------------

> For up to the minute detrails, add the COH3 calendar to your own calendar using [Google](https://calendar.google.com/calendar/u/0/r?cid=6ureum96qhgf13kj820i61ovq8@group.calendar.google.com) or [iCal](https://calendar.google.com/calendar/ical/6ureum96qhgf13kj820i61ovq8%40group.calendar.google.com/public/basic.ics) for iOS users. Or join us on [Facebook](https://www.facebook.com/groups/527235744035261/) and [WhatsApp](https://chat.whatsapp.com/JXtmP6IyNlm9q8H7sidqH5).
