# on:
#  schedule:
#    - cron: '0 10 * * 1' # Run every Monday at 10 am UTC

on:
  push:
    branches: main

jobs:
  run_email_sender:
    runs-on: ubuntu-latest

    steps:
    
      - name: Check out repository
        uses: actions/checkout@v3
      
      - name: Set up Pandoc
        uses: r-lib/actions/setup-pandoc@v2
        
      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Cache packages
        uses: actions/cache@v3 # Cache packages
        with:
          path: ~/.local/share/renv
          key: ${{ runner.os }}-renv-${{ hashFiles('**/renv.lock') }}
          restore-keys: |
            ${{ runner.os }}-renv-

      - name: Setup renv # Set up R env to install packages
        run: |
          R -e 'install.packages("renv")'
          R -e 'renv::restore()'

      - name: Install pandoc and pandoc citeproc
        run: |
          brew install pandoc
          brew install pandoc-citeproc

      - name: Render email
        run: Rscript -e 'source("R/send_email.R")'
        env:
          GMAIL_APP_PASSWORD: ${{ secrets.GMAIL_APP_PASSWORD }}
