# on:
#  schedule:
#    - cron: '0 10 * * 1' # Run every Monday at 10 am UTC

on:
  push:
    branches: main

jobs:
  run_email_sender:
    runs-on: ubuntu-latest

    steps:
    
      - name: Check out repository
        uses: actions/checkout@v3
      
      - name: Set up R
        uses: r-lib/actions/setup-r@master # Set up R runtime
        with:
          r-version: 'release'

      - name: Setup renv # Set up R env to install packages
        run: |
          install.packages('remotes')
          remotes::install_github("rstudio/renv")
        shell: Rscript {0}
        
      - uses: actions/cache@v2 # Cache packages
        with:
          path: ~/.local/share/renv
          key: ${{ runner.os }}-renv-${{ hashFiles('**/renv.lock') }}
          restore-keys: |
            ${{ runner.os }}-renv-

      - name: Install dependencies # Install the dependencies 
        run: renv::restore()
        shell: Rscript {0}

      - name: Render email
        run: Rscript -e 'source("R/send_email.R")'
        env:
          GMAIL_APP_PASSWORD: ${{ secrets.GMAIL_APP_PASSWORD }}
