# on:
#  schedule:
#    - cron: '0 10 * * 1' # Run every Monday at 10 am UTC

# on:
#  push:
#   branches: main

# on:
#  schedule:
#   - cron: '0 16 * * *' # Run every day at 4pm UTC

jobs:
  run_email_sender:
    runs-on: ubuntu-latest

    steps:
    
      - name: Check out repository
        uses: actions/checkout@v3
        
      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: 'renv' # Use the version recorded in the renv.lock file
      
      - name: Set up Pandoc
        uses: r-lib/actions/setup-pandoc@v2

      - name: Cache packages
        uses: actions/cache@v3 # Cache packages
        with:
          path: ~/.local/share/renv
          key: ${{ runner.os }}-renv-${{ hashFiles('**/renv.lock') }}
          restore-keys: |
            ${{ runner.os }}-renv-

      - name: Setup renv # Set up R env to install packages
        run: |
          R -e 'install.packages("renv")'
          R -e 'renv::restore()'

      - name: Render email
        run: |
          source("R/send_email.R")
        shell: Rscript {0} 
        env:
          GMAIL_APP_PASSWORD: ${{ secrets.GMAIL_APP_PASSWORD }}

  keepalive-job:
    name: Keepalive Workflow
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - uses: actions/checkout@v4
      - uses: gautamkrishnar/keepalive-workflow@v2